version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: 'directly'
      MYSQL_USER: 'directly'
      MYSQL_DATABASE: 'andre'

  redis:
    image: redis:5.0.5-alpine
    restart: always

  rabbit:
    image: rabbitmq:3
    restart: always
    ports: [ '15672:15672' ]

  andre:
    image: andre:latest
    ports: [ '8080:8080' ]
    environment:
      ENVIRONMENT: 'test'
      DB_HOSTNAME: 'db'
      DB_USERNAME: 'directly'
      DB_PASSWORD: 'directly'
      REDIS_HOSTNAME: 'redis'
      RABBIT_HOSTNAME: 'rabbit'
      RABBIT_USERNAME: 'guest'
      RABBIT_PASSWORD: 'guest'
      LOG_LEVEL: 'DEBUG'
    depends_on:
      - db
      - redis
      - rabbit
    links:
      - db
      - redis
      - rabbit
