dataSource:
    dbCreate: none
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://${DB_HOSTNAME}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&nullNamePatternMatchesAll=true&useSSL=false
    username: ${DB_USERNAME}
    password: "${DB_PASSWORD}"
    pooled: true
    properties:
        validationQuery: SELECT 1
        testOnBorrow: true
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 1800000
        minEvictableIdleTimeMillis: 1800000
        numTestsPerEvictionRun: 3
        maxActive: 150
        maxIdle: 25
        minIdle: 20
        initialSize: 20
        maxWait: 10000

---
grails:
    redis:
        host: ${REDIS_HOSTNAME}
        port: 6380
        database: 1
        pooled: true
        usePool: true
        resources: 15
        timeout: 5000
        poolConfig:
            maxIdle: 10
            minIdle: 5
            testWhileIdle: true
            testOnBorrow: true
            testOnReturn: true
            numTestsPerEvictionRun: 10
            timeBetweenEvictionRunsMillis: 60000

---
rabbitmq:
    enabled: false
