dataSource:
    dbCreate: none
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useUnicode=true&characterEncoding=UTF-8&nullNamePatternMatchesAll=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pooled: true
    properties:
        validationQuery: SELECT 1
        testOnBorrow: true
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 1800000
        minEvictableIdleTimeMillis: 1800000
        numTestsPerEvictionRun: 3
        maxActive: ${DB_MAXACTIVE}
        maxIdle: ${DB_MAXIDLE}
        minIdle: ${DB_MINIDLE}
        initialSize: ${DB_INITIALSIZE}
        maxWait: ${DB_MAXWAIT}

---
quartz:
    autoStartup: false

---
rabbitmq:
    enabled: false
